// <auto-generated />
using System;
using CompleteProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompleteProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250618140511_AddBugAndFeatureInheritance")]
    partial class AddBugAndFeatureInheritance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CompleteProject.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItem");

                    b.HasDiscriminator<string>("Discriminator").HasValue("TodoItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CompleteProject.Models.Bug", b =>
                {
                    b.HasBaseType("CompleteProject.Models.TodoItem");

                    b.Property<int>("AffectedUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AttachedBugId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScreenshotUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("AttachedBugId");

                    b.HasDiscriminator().HasValue("Bug");
                });

            modelBuilder.Entity("CompleteProject.Models.Feature", b =>
                {
                    b.HasBaseType("CompleteProject.Models.TodoItem");

                    b.Property<int?>("AttachedFeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.HasIndex("AttachedFeatureId");

                    b.HasDiscriminator().HasValue("Feature");
                });

            modelBuilder.Entity("CompleteProject.Models.Bug", b =>
                {
                    b.HasOne("CompleteProject.Models.Bug", "AttachedBug")
                        .WithMany()
                        .HasForeignKey("AttachedBugId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AttachedBug");
                });

            modelBuilder.Entity("CompleteProject.Models.Feature", b =>
                {
                    b.HasOne("CompleteProject.Models.Feature", "AttachedFeature")
                        .WithMany()
                        .HasForeignKey("AttachedFeatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AttachedFeature");
                });
#pragma warning restore 612, 618
        }
    }
}
